name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - ipycanvas
  - numpy==1.22.4
  - scipy==1.8.1
  - matplotlib==3.5.2
  - scikit-learn==1.1.1
  - ipywidgets==8.1.2
  - pandas==1.4.2 
