name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - ipycanvas
  - numpy==1.26.0
  - scipy
  - matplotlib
  - scikit-learn
  - ipywidgets
  - pandas 
